nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['*']  # In production, specify your React app's URL
    allow_methods: ['POST', 'GET', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['*']
      allow_methods: ['POST', 'GET', 'OPTIONS']
      allow_headers: ['Content-Type', 'Authorization']